# Generated by Django 4.0.3 on 2022-03-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='status',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('HOST', 'HOST')], default='CUSTOMER', max_length=10),
        ),
    ]
