# Generated by Django 4.0.3 on 2022-03-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='iligiblity',
            field=models.BooleanField(default=False),
        ),
    ]
