# Generated by Django 4.0.3 on 2022-03-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairapp', '0009_remove_hairsalon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='rators',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='total_customers',
            field=models.IntegerField(default=0),
        ),
    ]
