# Generated by Django 4.0.3 on 2022-03-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairapp', '0012_remove_hairsalon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='image',
            field=models.ImageField(default='salons_pics/default.jpg', upload_to=''),
        ),
    ]
