# Generated by Django 4.0.3 on 2022-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairapp', '0016_alter_hairsalon_available_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hairsalon',
            old_name='image',
            new_name='salon_image',
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='Available_services_list',
            field=models.TextField(default='None'),
        ),
    ]
