# Generated by Django 4.0.3 on 2022-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairapp', '0018_remove_hairsalon_available_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='crediblity',
            field=models.IntegerField(default=2),
        ),
    ]
