# Generated by Django 4.0.3 on 2022-03-13 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hairapp', '0021_alter_hairsalon_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairsalon',
            name='Available_services_list',
        ),
        migrations.RemoveField(
            model_name='hairsalon',
            name='Reservation',
        ),
        migrations.RemoveField(
            model_name='hairsalon',
            name='customer_queue',
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairapp.hairsalon')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairapp.hairsalon')),
                ('reserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
