# Generated by Django 4.0.3 on 2022-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairapp', '0023_hairsalon_name_alter_hairsalon_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='reserve_type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
