# Generated by Django 4.0.3 on 2022-03-11 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='User_pics/default.jpg', upload_to='User_pics')),
                ('status', models.CharField(default='CUSTOMER', max_length=100)),
                ('reservation', models.CharField(default='None', max_length=500)),
                ('phone_number', models.CharField(default='+251', max_length=20)),
                ('crediblity', models.IntegerField(default=3)),
                ('hairsalon', models.CharField(default='None', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
