# Generated by Django 4.0.3 on 2022-03-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairusers', '0002_alter_userpage_phone_number_alter_userpage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='image',
            field=models.ImageField(default='defaultU.jpg', upload_to='User_pics'),
        ),
    ]
