# Generated by Django 4.0.3 on 2022-03-11 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NONE', max_length=100)),
                ('customer_queue', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=3)),
                ('location', models.CharField(default='Ethiopia', max_length=100)),
                ('Available_services', models.CharField(default='NONE', max_length=500)),
                ('Reservation', models.TextField(default='NONE')),
                ('hostname', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
