# Generated by Django 4.0.3 on 2022-03-11 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hairapp', '0003_remove_hairsalon_hostname_hairsalon_salon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairsalon',
            name='salon',
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='Owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
