# Generated by Django 4.0.3 on 2022-03-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairapp', '0004_remove_hairsalon_salon_hairsalon_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairsalon',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
