# Generated by Django 4.0.3 on 2022-03-12 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hairapp', '0006_remove_hairsalon_owner_hairsalon_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairsalon',
            name='salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
