# Generated by Django 4.0.3 on 2022-03-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairapp', '0013_hairsalon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairsalon',
            name='image',
            field=models.ImageField(default='defaultS.jpg', upload_to='salons_pics'),
        ),
    ]
