# Generated by Django 4.0.3 on 2022-03-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairapp', '0019_hairsalon_crediblity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
